server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git: #default
          uri: ENC(bdmJoKBdlVr73s3mqmoUM+x0tHQkFVp182YiDbQIYcvZKTgy5kxV6MRQO+zQFhO2OEtFsjkAaGo=)
          username: ENC(d2IM6gDqSIXJAaWijxYzKA==)
          password: ENC(jTO/0HgYmORW8MA2DL1phlAilH8uSWQ2xYhZ+gLcltgndgasZ5L+krePRwVzviLDwtX3btSwH70=)
          default-label: master #기본이 main 브랜치이므로 master 브랜치에서 가져오기 위해 설정
        bootstrap: true
  rabbitmq:
    host: fluffit.shop
    port: 5672
    username: ENC(7CDqSrW1frk32qx8yIyHqA==)
    password: ENC(h8qqcxuF8aPm5dhKVFfLmMbYg2paxNem)

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh, refresh, metrics

jasypt:
  key: ${JASYPT_KEY}
