pipeline {
    agent any

    stages {
        stage('Gradle build') {
            steps {
                dir('backend/FluffitFlupet') {
                    sh 'chmod +x ./gradlew'
                    sh './gradlew clean build'
                }
            }
        }

        stage('Docker image build') {
            steps {
                dir('backend/FluffitFlupet') {
                    sh "docker stop flupet || true && docker rm flupet || true"
                    sh 'docker rmi flupet || true'
                    sh 'docker build -t flupet .'
                }
            }
        }

        stage('Docker container run') {
            steps {
                dir('backend/FluffitFlupet') {
                    sh 'docker run -d -p 8081:8080 --name flupet -e TZ=Asia/Seoul --network develop-net flupet'
                }
            }
        }

        stage('Cleanup dangling images') {
            steps {
                sh 'docker image prune -f'
            }
        }
    }
}


