pipeline {
    agent any

    stages {
        stage('Gradle build') {
            steps {
                dir('backend/FluffitFlupet') {
                    sh 'chmod +x ./gradlew'
                    sh './gradlew clean build'
                }
            }
        }

        stage('Docker image build') {
            steps {
                dir('backend/FluffitFlupet') {
                    sh "docker stop fluffitflupet || true && docker rm fluffitflupet || true"
                    sh 'docker rmi fluffitflupet || true'
                    sh 'docker build -t fluffitflupet .'
                }
            }
        }

        stage('Docker container run') {
            steps {
                dir('backend/FluffitFlupet') {
                    sh 'docker run -d -p 8082:8080 --name fluffitflupet fluffitflupet'
                }
            }
        }

        stage('Cleanup dangling images') {
            steps {
                sh 'docker image prune -f'
            }
        }
    }
}


