pipeline {
    agent any

    stages {
        stage('Gradle build') {
            steps {
                dir('backend/FluffitBattle') {
                    sh 'chmod +x ./gradlew'
                    sh './gradlew clean build'
                }
            }
        }

        stage('Docker image build') {
            steps {
                dir('backend/FluffitBattle') {
                    sh "docker stop battle || true && docker rm battle || true"
                    sh 'docker rmi battle || true'
                    sh 'docker build -t battle .'
                }
            }
        }

        stage('Docker container run') {
            steps {
                dir('backend/FluffitBattle') {
                    sh 'docker run -d -p 8082:8080 --name battle -e TZ=Asia/Seoul --network develop-net battle'
                }
            }
        }
        stage('Cleanup dangling images') {
            steps {
                sh 'docker image prune -f'
            }
        }
    }
}

