pipeline {
    agent any

    stages {
        stage('Gradle build') {
            steps {
                dir('backend/FluffitBattle') {
                    sh 'chmod +x ./gradlew'
                    sh './gradlew clean build'
                }
            }
        }

        stage('Docker image build') {
            steps {
                dir('backend/FluffitBattle') {
                    sh "docker stop fluffitbattle || true && docker rm fluffitbattle || true"
                    sh 'docker rmi fluffitbattle || true'
                    sh 'docker build -t fluffitbattle .'
                }
            }
        }

        stage('Docker container run') {
            steps {
                dir('backend/FluffitBattle') {
                    sh 'docker run -d -p 8081:8080 --name fluffitbattle fluffitbattle'
                }
            }
        }
        stage('Cleanup dangling images') {
            steps {
                sh 'docker image prune -f'
            }
        }
    }
}

