pipeline {
    agent any
    
    environment {
        JASYPT_KEY = credentials('JASYPT_KEY')
        JKS_PWD = credentials('JKS_PWD')
        JKS_ALIAS = credentials('JKS_ALIAS')
    }

    stages {
        stage('Gradle build') {
            steps {
                dir('backend/FluffitConfig') {
                    sh 'chmod +x ./gradlew'
                    sh './gradlew clean build'
                }
            }
        }

        stage('Docker image build') {
            steps {
                dir('backend/FluffitConfig') {
                    sh "docker stop fluffitconfig  || true && docker rm fluffitconfig || true"
                    sh 'docker rmi fluffitconfig || true'
                    sh 'docker build --build-arg JASYPT_KEY=${JASYPT_KEY} --build-arg JKS_PWD=${JKS_PWD} --build-arg JKS_ALIAS=${JKS_ALIAS} -t fluffitconfig .'
                }
            }
        }

        stage('Docker container run') {
            steps {
                dir('backend/FluffitConfig') {
                    sh 'docker run -d -p 8088:8080 --network testnetwork --name fluffitconfig fluffitconfig'
                }
            }
        }
    }
}


