pipeline {
    agent any

    stages {
        stage('Gradle build') {
            steps {
                dir('backend/FluffitConfig') {
                    sh 'chmod +x ./gradlew'
                    sh './gradlew clean build'
                }
            }
        }

        stage('Docker image build') {
            steps {
                dir('backend/FluffitConfig') {
                    sh "docker stop FluffitConfig || true && docker rm FluffitConfig || true"
                    sh 'docker rmi FluffitConfig || true'
                    sh 'docker build -t FluffitConfig .'
                }
            }
        }

        stage('Docker container run') {
            steps {
                dir('backend/FluffitConfig') {
                    sh 'docker run -d -p 8088:8080 --name FluffitConfig FluffitConfig'
                }
            }
        }
    }
}


