pipeline {
    agent any

    stages {
        stage('Gradle build') {
            steps {
                dir('backend/FluffitMember') {
                    sh 'chmod +x ./gradlew'
                    sh './gradlew clean build'
                }
            }
        }

        stage('Docker image build') {
            steps {
                dir('backend/FluffitMember') {
                    sh "docker stop member || true && docker rm member || true"
                    sh 'docker rmi member || true'
                    sh 'docker build -t member .'
                }
            }
        }

        stage('Docker container run') {
            steps {
                dir('backend/FluffitMember') {
                    sh 'docker run -d -p 8080:8080 --name member -e TZ=Asia/Seoul --network develop-net member'
                }
            }
        }
        stage('Cleanup dangling images') {
            steps {
                sh 'docker image prune -f'
            }
        }
    }
}
